### PR TITLE
improve methods

### PR DESCRIPTION
**Pull request by bobCodeContributor**
This change is [Reviewable](https://reviewable.io/reviews/aliceCodeReviewer/numbers/1)

### CODE REVIEW

**Review by aliceCodeReviewer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alicecodereviewer/numbers/1)* status: all files reviewed, 3 unresolved discussions (waiting on @bobCodeContributor)

___
*[`numbers.go` line 1 at r1](https://reviewable.io/reviews/alicecodereviewer/numbers/1#-NkFICOP6-Q8-q1IJtIj:-NkFICOP6-Q8-q1IJtIk:bz1bs8o) ([raw file](https://github.com/alicecodereviewer/numbers/blob/691235dcc8e6ff62a06d0ddd42ad5ff8559ea40e/numbers.go#L1)):*
> ```Go
> package numbers
> ```

Consider distributing to few files:

Add.go
Mul.go
Div.go
___
*[`numbers.go` line 11 at r1](https://reviewable.io/reviews/alicecodereviewer/numbers/1#-NkFI3fN-bW5zPliKAFE:-NkFI3fN-bW5zPliKAFF:bgt0x54) ([raw file](https://github.com/alicecodereviewer/numbers/blob/691235dcc8e6ff62a06d0ddd42ad5ff8559ea40e/numbers.go#L11)):*
> ```Go
> }
> 
> func Mul(n1, n2 int) int {
> ```

Consider remaining to number1, number2.
___
*[`numbers.go` line 16 at r1](https://reviewable.io/reviews/alicecodereviewer/numbers/1#-NkFHvG2CDp8DNdz9GBA:-NkFHvG2CDp8DNdz9GBB:bo43umg) ([raw file](https://github.com/alicecodereviewer/numbers/blob/691235dcc8e6ff62a06d0ddd42ad5ff8559ea40e/numbers.go#L16)):*
> ```Go
> 		out = Add(out, n2)
> 	}
> 	return out
> ```

It might be simpler to do this:



_Suggestion:_
```Go
return n1 * n2
```

**Review by bobCodeContributor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alicecodereviewer/numbers/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aliceCodeReviewer)

___
*[`numbers.go` line 1 at r1](https://reviewable.io/reviews/alicecodereviewer/numbers/1#-NkFICOP6-Q8-q1IJtIj:-NkFIwvq9dwh_EGMoCwj:b-896fix) ([raw file](https://github.com/alicecodereviewer/numbers/blob/691235dcc8e6ff62a06d0ddd42ad5ff8559ea40e/numbers.go#L1)):*
<details><summary><i>Previously, aliceCodeReviewer wrote…</i></summary><blockquote>

Consider distributing to few files:

Add.go
Mul.go
Div.go
</blockquote></details>

Done.

**Review by aliceCodeReviewer — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alicecodereviewer/numbers/1)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @bobCodeContributor)

___
*[`mul.go` line 5 at r2](https://reviewable.io/reviews/alicecodereviewer/numbers/1#-NkFJt9Y4XCA1YkhXfRw:-NkFJt9Y4XCA1YkhXfRx:b-gr7akc) ([raw file](https://github.com/alicecodereviewer/numbers/blob/2e5afc0a32ce0112daf3ac8e3fedfd330811a04f/mul.go#L5)):*
> ```Go
> func Mul(n1, n2 int) int {
> 	out := 0
> 	for i := 0; i < n1; i++ {
> ```

You haven't changed it.

**Review by bobCodeContributor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alicecodereviewer/numbers/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @aliceCodeReviewer)

___
*[`mul.go` line 5 at r2](https://reviewable.io/reviews/alicecodereviewer/numbers/1#-NkFJt9Y4XCA1YkhXfRw:-NkFK83SAZkXNtjqqN8e:b-896fix) ([raw file](https://github.com/alicecodereviewer/numbers/blob/2e5afc0a32ce0112daf3ac8e3fedfd330811a04f/mul.go#L5)):*
<details><summary><i>Previously, aliceCodeReviewer wrote…</i></summary><blockquote>

You haven't changed it.
</blockquote></details>

Done.

**Review by aliceCodeReviewer — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alicecodereviewer/numbers/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobCodeContributor)

**Pull request merged**
